### ISSUE TITLE
Unable to boot to DSM automatically

### ISSUE THREAD

**Issue by ntsangkc** [fbelavenuto/arpl#446]
I am using QNAP TS-269L to flash the DSM.
Everything is ok but I have one problem it is stuck in the grub boot menu page. I have to press enter to boot to the DSM system while starting even though I have turned "true" on boot to DSM directly selection.

**Comment by arihid** [comment]
I have QNAP TS-269 Pro and I also have that issue too. I asked this in qnap forum ([link to my thread](https://forum.qnap.com/viewtopic.php?f=191&t=167535), you have to register first) but nobody answered. I thought it just my unit was faulty.

It seems the system is spamming some keyboard keypress in GRUB boot menu. I still can press enter key, and "e" key to edit the boot argument. When I bring up the boot argument editor, it would just spam "U" and I can't do anything.

This doesn't happen on my QNAP TS-469 Pro.

I have accepted the fate and just slap a cheap numeric keyboard to press enter key everytime I boot.

I also leaving a dot in case someone have a solution.

**Comment by wgbingo** [comment]
me too .boot in TS-269L

**Comment by DZ65367709** [comment]
With arpl 1.03beta and 3617xs, I get a problem, once I reboot the system  in command line, the power is on but it will stuck there, black in display. Then I have to reboot on “restart” button.
It’s not for every time, generally occurring after the system running for a period of time. When I physically shut it down and test to reboot in CL, very likely it reboots normally.
My master board is j1900, details as https://m.book118.com/html/2021/0206/7024160114003053.shtm (sorry for this version as no English one).
Anybody please help. Thanks.

**Comment by arihid** [comment]
I've just tested and by disabling UEFI boot, the countdown work like a charm!
@fbelavenuto I think it's safe to close the issue and pin the solution for future reference.

**Comment by DZ65367709** [comment]
I tried to change it to UEFI booting, but when I set bios to that, it can’t boot at all.As another trying, I shutdown the machine remotely , with command POWEROFF, and attempt to wake it up with command WOL， I observed: 1. It powered off,2. The light is on after a while, yet the display is dark—it’s a faked starting, just as with the command REBOOT.在 2023年2月19日，23:28，Arief Hidayat ***@***.***> 写道：﻿
I've just tested and by disabling UEFI boot, the countdown work like a charm!
@fbelavenuto I think it's safe to close the issue and pin the solution for future reference.

**Comment by arihid** [comment]
> I tried to change it to UEFI booting, but when I set bios to that, it can’t boot at all.As another trying, I shutdown the machine remotely , with command POWEROFF, and attempt to wake it up with command WOL， I observed: 1. It powered off,2. The light is on after a while, yet the display is dark—it’s a faked starting, just as with the command REBOOT.在 2023年2月19日，23:28，Arief Hidayat ***@***.***> 写道：﻿ I've just tested and by disabling UEFI boot, the countdown work like a charm! @fbelavenuto I think it's safe to close the issue and pin the solution for future reference. —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

I can't investigate this further as my TS-269 Pro unit has been sold few days back.
But I do have a video that shows the booting issue was solved.
Please see the attached video.
[![Click to play.](https://img.youtube.com/vi/hLsJ99beS6Q/0.jpg)](https://www.youtube.com/watch?v=hLsJ99beS6Q)

**Comment by arihid** [comment]
@DZ65367709 Have you tried the UEFI image from Pocopico's Redpill release?
What is your board make and model?

**Comment by DZ65367709** [comment]
﻿I use the release from: https://github.com/fbelavenuto/arpland HW figures as listed:https://blog.csdn.net/seaship/article/details/88354973So sorry that I couldn’t find the detailed dataset of this motherboard.Thanks.在 2023年3月7日，09:28，Arief Hidayat ***@***.***> 写道：﻿
@DZ65367709 Have you tried the UEFI image from Pocopico's Redpill release?
What is your board maker and model?

**Comment by DZ65367709** [comment]
It seems there’s no hopes to fix the problem and I want to give it up. Now I want to know if I can re-prepare the USB booting disk with the arpl image new release, yet all previous data and DSM OS still exist and no need to make any changes.As I am worried that if I re-build the USB booting system, all my data disks will not be recognized and be forced to re-formatted… which is not what I could afford.Thanks for your help.在 2023年3月7日，09:28，Arief Hidayat ***@***.***> 写道：﻿
@DZ65367709 Have you tried the UEFI image from Pocopico's Redpill release?
What is your board maker and model?

**Comment by arihid** [comment]
So you previously have a working DSM installation (despite the boot problem)?
Yes you can. You can just rebuild the loader to continue using your DSM installation. You can even swap the motherboard, as long as you use the same disks by not formatting them.

You can continue your current setup by using your current platform, MAC, SN, and DSM version.

But if you change your platform and SN, you'll see migration screen instead. It will migrate all of your apps and also can retain all of your settings if you wish to.

Using your real mac have WOL benefit over generated one, but you certainly can't login to Synology Account even if you put real SN in your installation.

You can't use lower version of loader for your current installation.

**Comment by DZ65367709** [comment]
Got it. Thank you.在 2023年3月8日，01:14，Arief Hidayat ***@***.***> 写道：﻿
So you previously have a working DSM installation (despite the boot problem)?
Yes you can. You can just rebuild the loader to continue using your DSM installation. You can even swap the motherboard, as long as you use the same disks by not formatting them.
You can continue your current setup by using your current platform, MAC, SN, and DSM version.
But if you change your platform and SN, you'll see migration screen instead. It will migrate all of your apps and also can retain all of your settings if you wish to.
Using your real mac have WOL benefit over generated one, but you certainly can't login to Synology Account even if you put real SN in your installation.
You can't use lower version of loader for your current installation.

**Comment by DZ65367709** [comment]
Now I realize that maybe the question comes from UEFI booting but not from others. Yesterday came the problem again after a power lost , and when I reboot it manually, I found the BIOS booting options changed, the first boot options was set HDD but not UEFI ~which I setup before the problem.I’d ever been prompted to disable UEFI, but it didn’t work, if I did so, the machine couldn’t boot up. Could I rebuild the booting USB via ARPL whith boot method of LEGACY  and how to operate? Thanks.在 2023年3月8日，01:14，Arief Hidayat ***@***.***> 写道：﻿
So you previously have a working DSM installation (despite the boot problem)?
Yes you can. You can just rebuild the loader to continue using your DSM installation. You can even swap the motherboard, as long as you use the same disks by not formatting them.
You can continue your current setup by using your current platform, MAC, SN, and DSM version.
But if you change your platform and SN, you'll see migration screen instead. It will migrate all of your apps and also can retain all of your settings if you wish to.
Using your real mac have WOL benefit over generated one, but you certainly can't login to Synology Account even if you put real SN in your installation.
You can't use lower version of loader for your current installation.

**Comment by DZ65367709** [comment]
After redo the arpl loader with the USB stick, now i can set BIOS booting via legacy,... and anyway, the problem resolved.
I can reboot the system any time anywhere.
The question please get it closed. Thank you.
And thanks for your concern.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fbelavenuto/arpl"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月19日(星期天) 晚上11:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [fbelavenuto/arpl] Unable to boot to DSM automatically (Issue #446)





 
I've just tested and by disabling UEFI boot, the countdown work like a charm!
 @fbelavenuto I think it's safe to close the issue and pin the solution for future reference.
