### ISSUE TITLE
I build DS3622xs+ when Booting...only 3 sec can connect ip and will disconnect

### ISSUE THREAD

**Issue by minimoonleaf** [fbelavenuto/arpl#701]
When Loading DSM Kernel...Booting... is displayed, the IP can be pinged for the first three seconds, and then the Ping will show disconnection and can no longer be connected.

But when I unplug all the hard disks, when Loading DSM Kernel...Booting... appears, I can ping for the first three seconds until there is a connection, and then it will be disconnected for 30 seconds to a few minutes, and then I can find it when I ping connection is back

My device:
CPU:12500
MB: Gigabyte Z690M AORUS ELITE DDR4
DIMM:ADATA 8G ECC-DIMM *4
HDD: Seagate 2.5 inch 500GB *3 (ST9500420AS)

If you need environment debugging, please contact me, or please tell me what files can be provided to you to confirm the problem.

Thanks.

**Comment by AuxXxilium** [comment]
You can post output of: "lspci -nnk" in loader and best you add addon "console" and do the same command there. i see your board has a i225/226 chip. so it should be supported.

i know there are some bugs with settings in bios: 1. disable memory remap 2. disable pxe 3. please use uefi boot and not csm 4. disbale fastboot and quiteboot

**Comment by kitamo1981** [comment]
Try with only 2x HDD
Its stop working when U have more than disk drivers.

**Comment by AuxXxilium** [comment]
> Try with only 2x HDD Its stop working when U have more than disk drivers.

this bug is fixed since about 2 months

**Comment by minimoonleaf** [comment]
1.Web connect IP:7681 and choose model 42962 and other setting...than addon "console".
2.Build the loader
3.Boot the loader...the screen wait 1 min display "ARPL console - wait..."
The screen shows ARPL console - wait...
After that, there is no response... Then continue to wait for about 5~10 minutes and the screen will all disappear

https://photos.app.goo.gl/8DDN7Ff76SCAPADGA

**Comment by AuxXxilium** [comment]
the console addon is has a bug. but you don't need it.

**Comment by AuxXxilium** [comment]
Your Networkchip is a?Am 11.04.2023 um 14:22 schrieb minimoonleaf ***@***.***>:﻿
I try remove addon:console and build and Booting...
In the display Welcome to Automated Redpill Loader v1.1-beta2a
Model:DS3622xs+
Build: 42962
Cmdline:
(There are many parameters displayed, so I won’t list them one by one)
IP:192.168.100.3
Loading Kernel:...
Booting...
***@***.***:/opt/arpl#
It can still input text in the first 3 seconds or so, at this time Ping IP will also show connection, but when 3 seconds pass, Ping will show disconnection, and screen can no longer input any text....

**Comment by AuxXxilium** [comment]
yes it is. but fixes won‘t be added as inplace update. you need to build a new stick. Am 11.04.2023 um 14:32 schrieb ada-mob ***@***.***>:﻿

this bug is fixed since about 2 months

really?
#632

**Comment by ada-mob** [comment]
> yes it is. but fixes won‘t be added as inplace update. you need to build a new stick

I did this, doesn't work :\

**Comment by AuxXxilium** [comment]
use arc from my github and try again

**Comment by kitamo1981** [comment]
Nope, its not fixed.

pon., 10 kwi 2023, 12:14 użytkownik Christian Schulthess <
***@***.***> napisał:

**Comment by AuxXxilium** [comment]
as i wrote before, try arc from my github and report again.

**Comment by ada-mob** [comment]
> use arc from my github and try again

xpe starts (model 3621xs+), detects the old installation (I previously used the ds1621+ model on arpl), suggests migration, and then an error occurs at the DSM installation stage: the file could not be installed, it may be corrupted. And it doesn't matter: migration with or without saving the configuration, downloading the pat file directly or substituting a local file

**Comment by AuxXxilium** [comment]
can you add a screenshot from sysinfo menu in loader please.

**Comment by ada-mob** [comment]
12.04.2023, 09:51, "Christian Schulthess" ***@***.***>:
can you add a screenshot from sysinfo menu in loader please.

**Comment by ada-mob** [comment]
https://pasteboard.co/lFCa3NsuK5Nl.jpg
https://pasteboard.co/khs6xT8oOoi3.jpg

**Comment by ada-mob** [comment]
> can you add a screenshot from sysinfo menu in loader please.

https://pasteboard.co/lFCa3NsuK5Nl.jpg
https://pasteboard.co/khs6xT8oOoi3.jpg

**Comment by AuxXxilium** [comment]
Three things we know:1. You Should disable this NVMe Raid device, there is an option in bios to set this back to normal nvme usage. 2. Please go to Edit User Config and enter in cmdline section: SataPortMap: 8 (you will see the formating of this and you have to add the same amount of spaces like the other commits in this section)3. if you get the controller disabled i mentioned in 1, you can select the DT model you used beforeAm 12.04.2023 um 09:12 schrieb ada-mob ***@***.***>:﻿
https://pasteboard.co/lFCa3NsuK5Nl.jpg
https://pasteboard.co/khs6xT8oOoi3.jpg

**Comment by ada-mob** [comment]
> Three things we know

1. NVMe not have Raid options in bios. I use it for ssd cache in DSM (work fine before with 2 disks or more disks on device tree models)
2. SataPortMap: 8 arpl and tinycore set automatically too, but it doesn't help in any way
3. DT model not satisfied with the fact that it does not support virtualization on intel

**Comment by AuxXxilium** [comment]
You should disable VMD.

https://download.asrock.com/Manual/RAID/H670M-ITXax/English.pdf

**Comment by ada-mob** [comment]
> You should disable VMD.

my H610 not have this options :\

**Comment by AuxXxilium** [comment]
![image](https://user-images.githubusercontent.com/67025065/231420413-5b17e3d7-f7f3-4b3f-903f-0ac9255261ab.jpeg)

it's your h610m-itx/ac

**Comment by ada-mob** [comment]
> it's your h610m-itx/ac

Yes, I looked at the manual and the pictures in it. However, there is no setting of this option
https://pasteboard.co/0Hk3I8IuIXEJ.jpg

What I did now: I performed a BIOS reset, did a clean bootloader installation and chose rs4021. Result: there is no nvme controller in sysinfo, DSM installation starts, but is also interrupted with an error at the pat file installation stage

**Comment by AuxXxilium** [comment]
this is strange. picture is from manual of your board. 

https://github.com/AuxXxilium/AuxXxilium/wiki/Settings:-Bios-and-UEFI

additional you can look here if something in your bios is different

**Comment by ada-mob** [comment]
> this is strange. 

I think the picture is some kind of common for all models of h610-based ASRock motherboards. I'm surprised too.

Additional BIOS settings according to your recommendations are also implemented

**Comment by AuxXxilium** [comment]
last option: try a different usb stick.

**Comment by ada-mob** [comment]
Hm) 
Of course I will try, but there are no problems with it with numerous installation with two disks or on device tree models

**Comment by AuxXxilium** [comment]
Don't know where the bug is.

**Comment by ada-mob** [comment]
https://xpenology.com/forum/topic/63402-error-trying-to-load-pat-at-55-failed-to-install-dsm-message/

I use always same port, problem only now

**Comment by ada-mob** [comment]
> you can add dbgutils in addons, try to install dsm.

+ add dbgutils
+ rebuild loader
+ start dsm, error on pat stage
- no smb access on this moment
+ restart xpe
+ boot in loader
+ have smb access
- no see logs directory
https://pasteboard.co/Hg3My9C5IUUF.jpg

**Comment by ada-mob** [comment]
> Don't know where the bug is.

Can you to implement this? https://xpenology.com/forum/topic/68078-script-improvement-thread-for-tgs-boot-waitsh-module/

**Comment by AuxXxilium** [comment]
bootwait is implamented since 6 days. and i fixed another bug that cause install fails on 5-8%.

**Comment by minimoonleaf** [comment]
> 您的 Networkchip 是？Am 11.04.2023 um 14:22 schrieb minimoonleaf ***@***.***>: 我嘗試刪除 addon:console 並構建和引導...在顯示中歡迎使用 Automated Redpill Loader v1.1-beta2a Model:DS3622xs+ Build: 42962 Cmdline: (顯示的參數很多，就不一一列舉了) IP:192.168.100.3 Loading Kernel:... Booting... ***@ ***.***:/opt/arpl# 前3秒左右還能輸入文字，此時Ping IP也會顯示連接，但過了3秒Ping就顯示斷開，屏幕可以不再輸入任何文本.... —直接回复此電子郵件，在 GitHub 上查看它，或取消訂閱。您收到此郵件是因為您發表了評論。消息 ID：***@***.***>

0000:00:00.0 Class 0600: Device 8086:4650 (rev 05)
0000:00:01.0 Class 0604: Device 8086:460d (rev 05)
0000:00:02.0 Class 0300: Device 8086:4690 (rev 0c)
0000:00:14.0 Class 0c03: Device 8086:7ae0 (rev 11)
0000:00:14.2 Class 0500: Device 8086:7aa7 (rev 11)
0000:00:15.0 Class 0c80: Device 8086:7acc (rev 11)
0000:00:15.1 Class 0c80: Device 8086:7acd (rev 11)
0000:00:15.2 Class 0c80: Device 8086:7ace (rev 11)
0000:00:15.3 Class 0c80: Device 8086:7acf (rev 11)
0000:00:16.0 Class 0780: Device 8086:7ae8 (rev 11)
0000:00:17.0 Class 0106: Device 8086:7ae2 (rev 11)
0000:00:19.0 Class 0c80: Device 8086:7afc (rev 11)
0000:00:19.1 Class 0c80: Device 8086:7afd (rev 11)
0000:00:1c.0 Class 0604: Device 8086:7ab8 (rev 11)
0000:00:1f.0 Class 0601: Device 8086:7a84 (rev 11)
0000:00:1f.3 Class 0403: Device 8086:7ad0 (rev 11)
0000:00:1f.4 Class 0c05: Device 8086:7aa3 (rev 11)
0000:00:1f.5 Class 0c80: Device 8086:7aa4 (rev 11)
0000:01:00.0 Class 0200: Device 15b3:1003
0000:02:00.0 Class 0200: Device 8086:15f3 (rev 03)
0001:09:00.0 Class 0106: Device 1b4b:9235 (rev 11)
0001:0c:00.0 Class 0106: Device 1b4b:9235 (rev 11)

**Comment by minimoonleaf** [comment]
> > 您的 Networkchip 是？Am 11.04.2023 um 14:22 schrieb minimoonleaf _**@**_._**>: 我嘗試刪除 addon:console 並構建和引導...在顯示中歡迎使用 Automated Redpill Loader v1.1-beta2a Model:DS3622xs+ Build: 42962 Cmdline: (顯示的參數很多，就不一一列舉了) IP:192.168.100.3 Loading Kernel:... Booting... _**@ _**.**_:/opt/arpl# 前3秒左右還能輸入文字，此時Ping IP也會顯示連接，但過了3秒Ping就顯示斷開，屏幕可以不再輸入任何文本.... —直接回复此電子郵件，在 GitHub 上查看它，或取消訂閱。您收到此郵件是因為您發表了評論。消息 ID：**_@**_.***>
> 
> 0000:00:00.0 Class 0600: Device 8086:4650 (rev 05) 0000:00:01.0 Class 0604: Device 8086:460d (rev 05) 0000:00:02.0 Class 0300: Device 8086:4690 (rev 0c) 0000:00:14.0 Class 0c03: Device 8086:7ae0 (rev 11) 0000:00:14.2 Class 0500: Device 8086:7aa7 (rev 11) 0000:00:15.0 Class 0c80: Device 8086:7acc (rev 11) 0000:00:15.1 Class 0c80: Device 8086:7acd (rev 11) 0000:00:15.2 Class 0c80: Device 8086:7ace (rev 11) 0000:00:15.3 Class 0c80: Device 8086:7acf (rev 11) 0000:00:16.0 Class 0780: Device 8086:7ae8 (rev 11) 0000:00:17.0 Class 0106: Device 8086:7ae2 (rev 11) 0000:00:19.0 Class 0c80: Device 8086:7afc (rev 11) 0000:00:19.1 Class 0c80: Device 8086:7afd (rev 11) 0000:00:1c.0 Class 0604: Device 8086:7ab8 (rev 11) 0000:00:1f.0 Class 0601: Device 8086:7a84 (rev 11) 0000:00:1f.3 Class 0403: Device 8086:7ad0 (rev 11) 0000:00:1f.4 Class 0c05: Device 8086:7aa3 (rev 11) 0000:00:1f.5 Class 0c80: Device 8086:7aa4 (rev 11) 0000:01:00.0 Class 0200: Device 15b3:1003 0000:02:00.0 Class 0200: Device 8086:15f3 (rev 03) 0001:09:00.0 Class 0106: Device 1b4b:9235 (rev 11) 0001:0c:00.0 Class 0106: Device 1b4b:9235 (rev 11)

Onboard 2.5G
0000:02:00.0 Class 0200: Device 8086:15f3 (rev 03)
I225-v
